# Generated by Django 5.2.6 on 2026-01-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_bid_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
