# Generated by Django 5.2.6 on 2026-01-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_unused_pageview"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency_preference",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("JPY", "Japanese Yen"),
                    ("AUD", "Australian Dollar"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
